# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: demo-config
# data:
#   greeting: Hola

apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  GREETING: Hallo
  VAR1: value1
  var2: value2
