# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: demo
#   labels:
#     app: demo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: demo
#   template:
#     metadata:
#       labels:
#         app: demo
#     spec:
#       containers:
#         - name: demo
#           image: ondiacademy/demo:hello
#           ports:
#             - containerPort: 8888

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: demo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: demo
#   template:
#     metadata:
#       labels:
#         app: demo
#     spec:
#       containers:
#         - name: demo
#           image: ondiacademy/demo:hello-config-env
#           ports:
#             - containerPort: 8888
#           env:
#             - name: GREETING
#               value: Hallo Kumpel

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: demo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: demo
#   template:
#     metadata:
#       labels:
#         app: demo
#     spec:
#       containers:
#         - name: demo
#           image: ondiacademy/demo:hello-config-env
#           ports:
#             - containerPort: 8888
#           env:
#             - name: GREETING
#               valueFrom:
#                 configMapKeyRef:
#                   name: demo-config
#                   key: greeting

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: ondiacademy/demo:hello-config-env
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: demo-config
