apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data: # best practice
  username: YWRtaW4= # base64
  password: MWYyZDFlMmU2N2Rm # base64
# stringData:
# username: admin
# password: '1f2d1e2e67df'
